apiVersion: v1
kind: Service
metadata:
  name: jlpt-helper-service
  labels:
    app: jlpt-helper
spec:
  type: LoadBalancer  # minikube tunnel과 함께 사용
  selector:
    app: jlpt-helper
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
